API call errors now return the error message

diff --git a/footy b/footy
--- a/footy
+++ b/footy
@@ -2,7 +2,7 @@
 
 # == SET VARIABLES ==
 API=https://api.football-data.org/v2
-API_KEY="X-Auth-Token: $(cat $HOME/.config/footy/api_key.txt)"
+API_KEY="X-Auth-Token: $(cat $HOME/.config/footy/api-key.txt)"
 FOOTY=$(basename "$0")
 FOOTY_FULL="$0"
 USAGE="$FOOTY [-s <league> | -l | -t <league> | -k <api-key> | -h]"
@@ -25,7 +25,7 @@ shorthelp()
 	-m <+days>|<-days>  Prints upcoming ('+' prefix) or previous ('-' prefix) matches.
 	-l                  Prints all supported leagues.
 	-t <league>         Prints all teams in a league (use league's code or id).
-	-k <api-key>        Saves the api-key to $HOME/.config/footy/api_key.txt
+	-k <api-key>        Saves the api-key to $HOME/.config/footy/api-key.txt
 	-h                  Prints this user documentation.
 	EOF
 	exit 0
@@ -34,35 +34,47 @@ shorthelp()
 set_key()
 {
 	mkdir -p $HOME/.config/footy
-	echo "${OPTARG}" > $HOME/.config/footy/api_key.txt
+	echo "${OPTARG}" > $HOME/.config/footy/api-key.txt
 	exit 0
+}
+
+api_call()
+{
+	JSON=$(curl -sH "$API_KEY" $API/$1)
+	ERROR=$(echo "$JSON" | jq -r 'if .message != null then .message else "false" end')
+	if [ "$ERROR" = "false" ]; then
+		echo "$JSON"
+	else
+		1>&2 echo "$ERROR"
+		exit 1
+	fi
 }
 
 leagues()
 {
-	curl -sH "$API_KEY" $API/competitions | \
+	echo "$(api_call competitions)" | \
 		jq -r '.competitions[] | "\(.area.name),\(.name),\(.code),\(.id),\(.plan)"' | \
 		awk '{ $3 = ($3 == "null" ? "" : $3); $6 = ($5 == "TIER_ONE" ? "Free" : "" ) } 1' FS="," OFS="," | \
-		column -ts "," -N Area,Name,Code,Id,Plan,Price -R Id -H Plan
+		column -ts "," -N Area,Name,Code,Id,Plan,Price -H Plan
 	exit 0
 }
 
 teams()
 {
-	COMP=${OPTARG}
-	curl -sH "$API_KEY" $API/competitions/$COMP/teams | \
+	COMPETITION=${OPTARG}
+	echo "$(api_call competitions/$COMPETITION/teams)" | \
 		jq -r '.teams[] | "\(.name),\(.tla),\(.id)"' | \
 		awk '{ $2 = ($2 == "null" ? "" : $2) } 1' FS="," OFS="," | \
-		column -ts "," -N Name,Code,Id -R Id
+		column -ts "," -N Name,Code,Id
 	exit 0
 }
 
 standings()
 {
-	COMP=${OPTARG}
-	curl -sH "$API_KEY" $API/competitions/$COMP/standings | \
+	COMPETITION=${OPTARG}
+	echo "$(api_call competitions/$COMPETITION/standings)" | \
 		jq -r '.standings[0].table[] | "\(.position),\(.team.name),\(.playedGames),\(.won),\(.draw),\(.lost),\(.points)"' | \
-		column -ts "," -N Pos,Team,P,W,D,L,Pts -R Pos,P,W,D,L,Pts
+		column -ts "," -N Pos,Team,P,W,D,L,Pts
 	exit 0
 }
 
